version: '3'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    image: api-gateway
    ports:
      - "8765:8765"
    networks:
      - my-network
    depends_on:
      server-discovery:
        condition: service_healthy
    volumes:
      - ./target/:/app/target

  discovery-server:
    container_name: discovery-server
    image: madchicken98/discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge